before_script:
  - git submodule update --init --recursive
  - git submodule sync --recursive

stages:
- build
- clean
  
debug:
  stage: build
  script:
  - make debug
  when: on_success
  except:
  - tags
  
release:
  stage: build
  script:
  - make release
  when: on_success
  except:
  - tags

clean:
  stage: clean
  script:
  - make clean
  when: always
  except:
  - tags
