before_script:
  - git submodule update --init --recursive
  - git submodule sync --recursive

stages:
- build
- doc
- clean
  
debug:
  stage: build
  script:
  - make debug
  when: on_success
  except:
  - tags
  
release:
  stage: build
  script:
  - make release
  when: on_success
  except:
  - tags

doc:
  stage: doc
  script:
  - make doc
  - rm -r /var/www/doc/MATS
  - mkdir -p /var/www/doc/MATS/downloads
  - cp -r doc/gen/html/* /var/www/doc/MATS/
  - cp MATS-doc.* /var/www/doc/MATS/downloads/
  when: on_success
  artifacts:
    paths:
    - MATS-doc.*
  except:
  - tags

clean:
  stage: clean
  script:
  - make clean
  when: always
  except:
  - tags
